### ISSUE TITLE
failed to enable component: ENOSPC

### ISSUE THREAD

**Issue by jhagberg** [silvanmelchior/RPi_Cam_Web_Interface#17]
Just followed your guide updated rasbian and cloned git

But cant start camera

raspimjpeg 
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC

What is missing?

**Comment by wilz7** [comment]
Hey how did you do that

**Comment by roberttidey** [comment]
Are you having a problem starting the software and you are getting the ENOSPC error message?

If so then the most likely cause is that you do not have the camera hardware interface actually working. This can be one of a number of things.

Not enabling camera support in raspi-config
Camera cables not inserted correctly
Small ribbon on camera module loose (press down)
Marginal power supply or poor USB power lead

Also try running a test with raspistill to check the camera

**Comment by wilz7** [comment]
HI managed to solve it i had to do a reboot...
