### ISSUE TITLE
No unattended installation possible anymore due to heavy usage of dialogs

### ISSUE THREAD

**Issue by konstantinj** [silvanmelchior/RPi_Cam_Web_Interface#182]
Hi there,

I wanted to create a docker image for the rpicam. Unfortunately an unattended installation is not possible anymore since you're using dialog quite heavily and it's not possible to bypass that with command line options. Only possibility would be using except but that's quite unfortunate. Could you add support for an unattended installation again?

**Comment by roberttidey** [comment]
miraaz has done quite a bit of work making it more 'friendly' for the average interactive install as before it required quite a bit of post-install work if wanting to customise the install a bit. An unattended install option was going to be added at the end of this work but hasn't happened yet.

I'll have a look to see if that can be done sooner.

**Comment by miraaz** [comment]
Yea sorry. I have currently very little time because i changed my work in real life... I need now learn new work. So i away little time.

**Comment by miraaz** [comment]
I look on it when i find little more time...

**Comment by konstantinj** [comment]
Hi, no problem. It's working for me with expect. Unfortunately expect is not running in Docker because of the dumb term. But I won't give up. Since docker is working great on rpi now I think that might me appreciated by others as well.

**Comment by konstantinj** [comment]
Hi, finally "some" month later I have a working docker version now: https://github.com/konstantinj/RPi_Cam_Web_Interface

Just wanted to let you know.
