### ISSUE TITLE
no camera image

### ISSUE THREAD

**Issue by mikolaskova** [silvanmelchior/RPi_Cam_Web_Interface#206]
Hello, 
unfortunately, after installation I can see the webinterface, it says loading, but then no image is loaded. What can I do to get the camera image?
I'm running it on an Raspberry Pi B, wheezy. The cam is the Raspberry Camera Rev. 1.3.
Thanks and regards, 
Adriana

**Comment by mikolaskova** [comment]
Sorry- I did not see, that autostart was disabled and camera stopped in the default configuration. When changing to autostart enabled and/or started camera, everything works perfect! Thanks!

**Comment by roberttidey** [comment]
I was just adding an extra trouble shooting section in the wiki for this condition.

Good to hear you fixed it anyway.
