### ISSUE TITLE
Issue with Image quality entry

### ISSUE THREAD

**Issue by jmr123** [silvanmelchior/RPi_Cam_Web_Interface#21]
On the control web page if I enter to the Image quality box anything except 0 - 100 it pop ups an error "Error in RaspiMJPEG: Could not set quality
Restart RASPIMJPEG(./RPi_Cam_web_interface_Installer.sh start) or the whole RPi."

Also if I enter something allowed (eg. 90), and then I clear the box and hit OK, same error.

**Comment by silvanmelchior** [comment]
Yes, there is no input-filtering at the moment in raspimjpeg. So if you want you can add it to my forked userland and make a push-request
