### ISSUE TITLE
MP4Box keywords and numbers

### ISSUE THREAD

**Issue by Berryfier** [silvanmelchior/RPi_Cam_Web_Interface#226]
To make the settings appear correctly in the web browser
the line in /etc/raspimjpeg
`#MP4Box false=leave as raw h264, background=box in background`
needs changing to
`#MP4Box Off=leave as raw h264, Background=box in background`
or
`#MP4Box 0=leave as raw h264, 1=box in background`

**Comment by roberttidey** [comment]
Updated. Thanks
