### ISSUE TITLE
Can't change Timelapse-Interval

### ISSUE THREAD

**Issue by p4trykx** [silvanmelchior/RPi_Cam_Web_Interface#25]
Timelapse-Interval input box on the web interface seems to be not working. Whatever I put in, it does not change. Is there a way to have 60s interval with timelaps.

**Comment by spikedrba** [comment]
@p4trykx are you trying to change it while the timelapse is running? I've just taken a quick look at the code and it seems to me the timelapse interval is only taken into consideration when you start the timelapse:

https://github.com/silvanmelchior/RPi_Cam_Web_Interface/blob/master/www/js/script.js#L123

in other words if you have a value in there, then start the timelapse and then change it, the change will never take effect. You need to stop the timelapse, change the interval and start again.

Also note that the setting is not preserved, which admittedly makes things confusing as you basically have no way to know what the timelapse is set to if you input something, start it, then close the page and re-open it.

Apart from that it seems to work fine for me.
