### ISSUE TITLE
subprocess.call("/home/pi/usb/webcam/makedogmovie.sh",  shell=True

### ISSUE THREAD

**Issue by dazbaker** [silvanmelchior/RPi_Cam_Web_Interface#257]
>subprocess.call("/home/pi/usb/webcam/makedogmovie.sh",  shell=True> i add this in  pi-timolo.py

hi every time i want to add this line i get a erro  File 
"./pi-timolo.py", line 289
    else:
       ^
subprocess.call("/home/pi/usb/webcam/makedogmovie.sh",  shell=True

**Comment by roberttidey** [comment]
I think this is posted in wrong project. Sounds like it should be in pi-timolo
