### ISSUE TITLE
New Timelapse Features

### ISSUE THREAD

**Issue by torstenhaase** [silvanmelchior/RPi_Cam_Web_Interface#26]
Thanks for this great piece of software! I have some ideas to improve the time-lapse feature, maybe you like some of them?

1) It would be great if you can download all pictures of a time-lapse at once. Maybe put them into a zip file after finishing the time-lapse
2) Can you set a length for the time-lapse? For example "make every 10s a picture for 3 hours". Or can you set a max amount of picture for example "make 1000 pictures, one every 10s"
3) Can you show the current details for a time-lapse, for example picture 234 of 1000 remaining time 1h53min
4) For the time-lapse it would be great if the pictures get a number instead of a timestamp, maybe you enter a name and the pictures are named "yourtimelapse0032"

Thanks & Regards
Torsten

**Comment by silvanmelchior** [comment]
Hi, thanks for your ideas.

Robert made many improvements to the timelapse-feature, he will push them soon
