### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by MartinDejmal** [silvanmelchior/RPi_Cam_Web_Interface#274]
When installing on Rasbian Jessie Lite there are some issues which cause overwriting permissions in entire filesystem. 

I did install to nginx and tried to setup destination directory. After entering /var/www/rpicam I got confirmation saying //var/www/rpicam - so I tried install again with entering just var/www/rpicam and then "IT" happened - whole filesystem is now owned by www-data and has garbled permissions.

I am not really fond of trying it again, so I cannot provide additional details.

**Comment by roberttidey** [comment]
You don't say which installation method you are using RPi_Cam_Web_Interface_Installer.sh or install.sh.

The wiki recommends using the install.sh. That is the only one I am supporting. For the first one you need to post a question on the forum for miraaz to check out.

**Comment by MartinDejmal** [comment]
Thanks Robert for your response. I am not sure, I spent hours with this in last few days trying this and that. I will give it try in a separate system again and let you know. 
I *think* that it was related to RPi_Cam_Web_Interface_Installer.sh.
