### ISSUE TITLE
Not an issue - but can't find a contact e-mail.

### ISSUE THREAD

**Issue by sh2515** [silvanmelchior/RPi_Cam_Web_Interface#30]
Hi
Best version of picamera security, well done.
I have a few - noob - questions I hope you might be able to help me with:
1) I heard this was using the picamera python API. If this is correct which is the file I need to find to have a look at to help me learn more on using the picamera with this software? Or which files are the ones controling the recording video?
2) rpimjpeg file. How do I view this file?
3) I have playing around with the streaming file from the python API picamera, but i am not sure how i am able to stream video without the need for the client side to not use VLC or such, how was you able to stream video to a web page?
4) where can I amend the overlay text? my white text is in the sky where it can't be read when bright

Thanks

**Comment by amm0nite** [comment]
1 and 2) The RPi Cam Web Interface gets its video from the raspimjpeg program. Rapimjpeg works directly with the GPU, it is compiled and the source is [here](https://github.com/silvanmelchior/userland/blob/master/host_applications/linux/apps/raspicam/RaspiMJPEG.c)
3) This works by loading a jpeg file in the web page and refreshing it at a high rate
4) /etc/raspimjpeg is the config file
