### ISSUE TITLE
Accessing the stream via a smartphone IP cam viewer

### ISSUE THREAD

**Issue by Chuckatron** [silvanmelchior/RPi_Cam_Web_Interface#304]
Is this possible? I've dug around inside the issues and forum thread and can't find anything. I know it's possible to load the webpage in the smartphone's browser, but that's a bit overkill. Is there a "raw" stream that can be accessed via an IP camera viewer?

**Comment by roberttidey** [comment]
The wiki indicates that by setting the ip to http://cameraip/rootfolder/min.php you will get a stream with none of the controls. This still relies on the javascript support at the client end.

**Comment by Chuckatron** [comment]
OK, thanks for the reply :-)
