### ISSUE TITLE
Downloading images after closing tab in Firefox

### ISSUE THREAD

**Issue by tom-2015** [silvanmelchior/RPi_Cam_Web_Interface#31]
Had this problem that Firexfox didn't stop downloading images after closing the webpage (tab). Had to restart Firefox to make it stop downloading the pictures.
Added:

```
window.onbeforeunload = function (){
    halted=1;
  };
```
to init() function in www/js/script.js
now it seems to stop when closing the tab.

**Comment by silvanmelchior** [comment]
Would be great if you could push the changes! Thanks
