### ISSUE TITLE
RPi Cam Web Interface coding suggestion

### ISSUE THREAD

**Issue by pishotta** [silvanmelchior/RPi_Cam_Web_Interface#312]
Have it working on Pi Zero doing long timelapse captures producing many thousands of images. At the start of the Convert (to video) option, the (in my installation) Apache web server issues commands in preview.php to copy those images to a temporary directory (e.g., t0000) before handing off the actual processing to gstreamer (or whatever). This copy process can take a LONG time and use a LOT of temporary space (GBs). So much so, that the server will often time out waiting for that step to complete and abort the whole conversion. Alas...

However, examining the code in preview.php, I realized that it was only necessary to create appropriately named symbolic links in that temporary directory back to the image files in their original "media" directory [php symlink() function instead of copy()]. This runs MUCH faster, uses virtually no additional space, and seems to work perfectly. I recommend it as a future patch. The spawned conversion command can still take a while, but that runs asynchronously, so not a problem for Apache.

Note: The gstreamer conversion process presents its own set of challenges, but that is another topic for another day.

-- Fred P.

**Comment by roberttidey** [comment]
That sounds like an excellent suggestion. I'll check out changing to that. 

Thanks
