### ISSUE TITLE
Arguments to sy macros

### ISSUE THREAD

**Issue by pishotta** [silvanmelchior/RPi_Cam_Web_Interface#324]
Hi

When I try to execute a macro with an argument through the FIFO path to raspimjpeg, e.g.,

                   echo "sy test.sh  foo" > /var/www/html/rpicam/FIFO

the log complains

                   Can't find macro /var/www/html/rpicam/macros/test.sh foo

but it works just fine without the " foo".  It's like it's interpreting the " foo" as part of the macro name instead of "foo" being an argument to it.

Or is it the case that you can't pass arguments to macros with the sy command in this way?  I can get the info to the macro in other ways, but thought I would ask in case I was missing something.

-- Fred P.

**Comment by roberttidey** [comment]
Currently it is checking for the existence of the macro in the macros folder before trying to execute it. 

The presence of the parameters on the sy is stopping that check working.

I'll have a look to see if the check can be made smarter.

**Comment by roberttidey** [comment]
Latest version allows the parameters on a sy macro

**Comment by pishotta** [comment]
Thanks.  Probably a good idea for that command.  Useful in general.
