### ISSUE TITLE
Special characters in camera annotation

### ISSUE THREAD

**Issue by WillemJann** [silvanmelchior/RPi_Cam_Web_Interface#326]
For my camera set-up, it would be nice if I can include special characters like `é` and `è` in the camera annotation setting. Currently these characters translate to `??` in the preview stream, e.g. `Héllo world` becomes `H??llo world`.

Is it possible to support these special characters? It has probably something to do with character encoding?

**Comment by roberttidey** [comment]
The annotation is rendered by the MMAL system camera software. We supply the string for each frame. The character set and encoding is not something we can control unfortunately. We can control colour and size.
