### ISSUE TITLE
PRi_Cam_Web_Interface not cloning

### ISSUE THREAD

**Issue by caesarx86** [silvanmelchior/RPi_Cam_Web_Interface#329]
Hi,

I'm having an issue installing the PRi_Cam_Web_Interface.
I did all the updates etc.
When i use the command on my Raspbian Jessie its not really doing anything:

![image](https://cloud.githubusercontent.com/assets/25968845/23240490/196150bc-f96e-11e6-948a-42bc979e6c72.png)

Any idea what my problem can be?

Thanks in advance!

Nick

**Comment by roberttidey** [comment]
Looks like the raspberry  is not reaching the internet for some reason.

Try ping github.com

To see if that can see the github site. CTRL-C will stop the pinging

**Comment by caesarx86** [comment]
Internet works fine and github is accessible:

![image](https://cloud.githubusercontent.com/assets/25968845/23277933/051b39d6-fa10-11e6-91bf-2a5cac419dd8.png)

**Comment by roberttidey** [comment]
I haven't seen a problem with the cloning part before. This is what the normal ouptut and I just rechecked it.

git clone https://github.com/silvanmelchior/RPi_Cam_Web_Interface.git
Cloning into 'RPi_Cam_Web_Interface'...
remote: Counting objects: 2330, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2330 (delta 2), reused 0 (delta 0), pack-reused 2316
Receiving objects: 100% (2330/2330), 3.88 MiB | 292.00 KiB/s, done.
Resolving deltas: 100% (1382/1382), done.
Checking connectivity... done.

Does it create a PRi_Cam_Web_Interface folder?

I'll check to see if it is possible to get any logging on the git clone process

**Comment by roberttidey** [comment]
Couple of other thoughts. I suspect this is not specific to this github repository but with any git clone process. It might be worth checking trying a different clone like wiringPi to see if that is the case.

Are you using a wifi connection or direct lan? There have been some reports of the routing getting confused if both are active and stopping the clone from proceeding. If you can try with just a wired connection.

Other users traced this down to a router problem which was resolved by rebooting their router.

**Comment by caesarx86** [comment]
I did a complete re-install of Raspbian and now it works.
Thanks!
