### ISSUE TITLE
Timelapse convert feature does not work

### ISSUE THREAD

**Issue by brunoaduarte** [silvanmelchior/RPi_Cam_Web_Interface#330]
I've started the timelapse function in the web panel and recorded a few images. Then i tried to click the convert button, it showed the "Busy" status and then the converted video link. But when i list the files at "/var/www/media/" it shows a zeroed file.

> pi@raspberrypi1ModelB:/var/www/media $ ls -nath
> total 900K
> drwxr-xr-x 2 33 33 4.0K Feb 23 18:11 .
> -rw-r--r-- 1 33 33    0 Feb 23 18:11 tl_0000_0001_20170223_180934.mp4
> -rw-r--r-- 1 33 33 9.9K Feb 23 18:11 tl_0000_0001_20170223_180934.mp4.v0000.th.jpg
> -rw-r--r-- 1 33 33 175K Feb 23 18:09 tl_0000_0005_20170223_180946.jpg
> -rw-r--r-- 1 33 33 170K Feb 23 18:09 tl_0000_0004_20170223_180943.jpg
> -rw-r--r-- 1 33 33 176K Feb 23 18:09 tl_0000_0003_20170223_180940.jpg
> -rw-r--r-- 1 33 33 170K Feb 23 18:09 tl_0000_0002_20170223_180937.jpg
> -rw-r--r-- 1 33 33 171K Feb 23 18:09 tl_0000_0001_20170223_180934.jpg
> -rw-r--r-- 1 33 33 9.9K Feb 23 18:09 tl_0000_0001_20170223_180934.jpg.t0000.th.jpg
> drwxr-xr-x 9 33 33 4.0K Feb 23 18:09 ..
> pi@raspberrypi1ModelB:/var/www/media $ 

I'm using latest

> RASPBIAN JESSIE LITE
> Minimal image based on Debian Jessie
> Version:January 2017
> Release date:2017-01-11
> Kernel version:4.4

I've manually installed "gstreamer" as it't not installed by default

> sudo apt-get install gstreamer1.0

Anything else i should do  ?

**Comment by pishotta** [comment]
You don't need the whole gstreamer1.0 package (it's huge).  Only needs gstreamer1.0-tools (smaller) which is installed with the install.sh script.  Probably doesn't hurt, though.

gstreamer-whatever  is temperamental.  Start with smaller image resolutions.  It'll abort if they're too big.  I use 1024x768.

-- Fred P.

**Comment by roberttidey** [comment]
Jessie full includes the normal gstreamer package but not the tools which convert needs and that is why the installer puts that piece in.

Jessie Lite does NOT include the gstreamer package. The tools piece is not sufficient. The easiest way with Lite is to install gstreamer 1.0 but this does also install quite a lot of other stuff which is not needed. It is possible to do a more selective install of just the particular components but that is quite a bit more complicated. So my advice is either to use full Jessie or put the gstreamer1.0 onto Lite. I normally do a full Jessie and then remove a lot of unrequired stuff which gets it back close to a Jessie Lite footprint. This is covered in the wiki, A single command can get rid of a lot of stuff.

As to the conversion process itself, the gstreamer method uses the GPU processor to do the conversion. A CPU only software conversion is very slow on the Raspberry Pi. Using the GPU does introduce some limitations. In particular high resolution formats above 1920 x 1080 will not work. Normally this is not too much of a restriction for time-lapse work as one wants videos that are normal video format (4 x 3, 16 x 9). If one wants to use very high resolution images then it is best to download the image set and convert using available tools on a PC or Mac.

**Comment by brunoaduarte** [comment]
Ok, thanks @pishotta and @roberttidey
