### ISSUE TITLE
Forum gone?!

### ISSUE THREAD

**Issue by piecam** [silvanmelchior/RPi_Cam_Web_Interface#35]
I couldn't access this forum any more.
The link resulted this,
Information: The requested topic does not exist. 

Forum: http://www.raspberrypi.org/forums/viewtopic.php?f=43&t=63276

What's happening?
tks

**Comment by spikedrba** [comment]
maybe it overflow the database for too many posts :)

**Comment by silvanmelchior** [comment]
Had the same problem, now it seems to work again
