### ISSUE TITLE
Absence of license

### ISSUE THREAD

**Issue by fcolecumberri** [silvanmelchior/RPi_Cam_Web_Interface#351]
You don't have any licence in this work, you just have some disclaimers in some scripts, I would sugest you to use a LGPL or a GPL licence. I ask you this because we are thinking on using this project as part of other proect and we need to know we can actually use it.

**Comment by roberttidey** [comment]
I'll check that out. Silvan Melchior was the original author, but has not been involved for the last couple of years.

**Comment by roberttidey** [comment]
My idea here on this is to use the MIT License which is short, simple and permissive. I am checking if silvan is OK with this.

**Comment by roberttidey** [comment]
SIlvan was OK with this so I have added MIT LIcense file

**Comment by fcolecumberri** [comment]
Thanks a lot
