### ISSUE TITLE
ServoBlaster arrows don't show up

### ISSUE THREAD

**Issue by Giudalpa** [silvanmelchior/RPi_Cam_Web_Interface#363]
I changed the file name from servo_off to servo_on, but the dirrectional arrows don't show up.

I'm using the version 6.3.13 and Raspbian Jessie 4.9.35

Thanks in advance.

**Comment by roberttidey** [comment]
Just tried that and it works OK for me.

Are you changing the file in the actual run time install folder? If you change the one in the installer folder that won't work; those are just files that get copied into the run time place.

So if you have installed in /var/www/html then you should do 
sudo mv /var/www/html/servo_off /var/www/html/server_on

**Comment by Giudalpa** [comment]
Thank you that was the problem! 

Cheers!
