### ISSUE TITLE
How to get version?

### ISSUE THREAD

**Issue by Lewiscowles1986** [silvanmelchior/RPi_Cam_Web_Interface#373]
How to get the version without running any code, seeing effects. 

A lot of repo's use releases, so I can issue a Git command to get the release, or checkout a specific release. It's kinda necessary for works I've mentioned in #333.

**Comment by legrosgore** [comment]
grep VERSION /var/www/html/config.php
?

**Comment by Lewiscowles1986** [comment]
:blush: that's used with cut util in the installer...
