### ISSUE TITLE
mmal_vc_component_create failed to create vc.ril.camera

### ISSUE THREAD

**Issue by Beschuitbus** [silvanmelchior/RPi_Cam_Web_Interface#379]
Hello,
installed the web interface on RPI-zero w.
When starting I get an error:
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: _component_create_core: could not create component 'vc.ril.camera' (1)
sh: 1: /var/www/html/macros/error_hard.sh: Permission denied

**Comment by roberttidey** [comment]
Don't worry about the 3rd permission denied error message. That is just it trying to execute a macro script when it encounters an error.

The first two indicate that it is not managing to connect to the Raspberry camera.

Have you enabled camera support in the Raspbian OS? It is also worth checking using raspivid or raspistill to see if the basic camera is working OK.

**Comment by Beschuitbus** [comment]
Hi Robert,
thanks for the quick responce, you're right, the camera cable is broken )-8
