### ISSUE TITLE
control from command line

### ISSUE THREAD

**Issue by Zacki84** [silvanmelchior/RPi_Cam_Web_Interface#386]
HI

I´m able to start/stop camera or videorecording or take a pic with the following command:
echo -n 'ca 0' >/var/www/html/FIFO
ru 0 or ru 1 => start/stop cam
ca 0 or ca 1 => start/stop rec
im => take pic

but when I try to change for example the Exposure Mode with 
echo -n 'em Night' >/var/www/html/FIFO
or
echo -n 'em Auto' >/var/www/html/FIFO

then I face an error message on the browser 

Why does this not work? I tried to change exposure while cam was streaming, and I tried to stop cam and change than, but its allways facing an error

Thanks

**Comment by roberttidey** [comment]
Commands that use text values like em have parameters that are case sensitive.

The values that you see in the Web browser are just the labels not the values sent in the commands

So using 'night' and 'auto' will work

If you look in command reference (on scheduler page then it has the valid values for each command.

**Comment by Zacki84** [comment]
thx, I got it

but I didn´t get Brightness running
echo -n 'br 60' >/var/www/html/FIFO
should be correct, but facing an error

**Comment by roberttidey** [comment]
brightness (br) works on mine.

Note you do not need the -n anymore; the software was modified to handle the line feeds, but it will work even if you use the -n

First check the brightness works OK from web interface. Then do the command line version again and let me know what error you get.

**Comment by Zacki84** [comment]
is working.

I insert a little break (time.sleep) in my python script between the EM line and the BR line, and its working now

Thanks

**Comment by roberttidey** [comment]
OK. If one does use LF between commands then the handler should accept those OK without worrying about pauses.
