### ISSUE TITLE
motion file directory creation for email alert using ssmtp 

### ISSUE THREAD

**Issue by fantyd** [silvanmelchior/RPi_Cam_Web_Interface#393]
Hi,

For creation of email alert using ssmtp, do i need to create to the same copy as RPi interface under media folder in order to work?

**The link below is the ssmtp creation path**
nano /home/pi/motion-files/emailme

**below is the guide reference link**
http://www.raspberry-pi-geek.com/Archive/2013/02/Working-with-the-Raspberry-Pi-camera-module/(offset)/8

**Comment by roberttidey** [comment]
you would put a copy of the emailer script in the macros folder. Rename it to motion_detect.sh as that is the default name.

It needs to be owned by www-data and have execution privileges as previously described.

The other thing that might stop it working is if www-data does not have privileges to run the mail program. One can add this privilege if necessary.
