### ISSUE TITLE
error message when test message from the Pi command line to telegram bot

### ISSUE THREAD

**Issue by fantyd** [silvanmelchior/RPi_Cam_Web_Interface#394]
Encounter error message when test message to start with by entering the following from the Pi command line (substituting with your API and chatid where relevant):

{"ok":false,"error_code":401,"description":"Unauthorized"}

**Comment by roberttidey** [comment]
Are you using quavoce telegram example or trying to send an email?

Either way the error message is because the server is rejecting your attempt to login. This can be just a mistake in the user / password being used, or a mail server may be wanting a particular form of login.

**Comment by fantyd** [comment]
I using quavoce, ok i would leave comment on his blog.
