### ISSUE TITLE
Security issue - datetime field does not sanitise input before passing to sudo

### ISSUE THREAD

**Issue by oleskiewicz** [silvanmelchior/RPi_Cam_Web_Interface#399]
Following #396, I have managed to execute a command on a Pi Zero W through time input field.

Time is changed through

```php
shell_exec("sudo date -s \"$timestr\"");
```

and `$timestr` is an unsanitised string from an AJAX request, passed directly to the `sudo` command.

Entering ``SOME DATE; `sudo shutdown now`;`` works and powers off the device, meaning other attacks can be performed.

This could be fixed by:

- only accepting input from a datetime-like widget
- sanitising the input on the backend

**Comment by roberttidey** [comment]
good point. I'll look into sanitising the timestring before executing it.

**Comment by roberttidey** [comment]
Latest version checks for valid date string and only executes if OK.
