### ISSUE TITLE
Motion detect trigger of LED light

### ISSUE THREAD

**Issue by fantyd** [silvanmelchior/RPi_Cam_Web_Interface#403]
Where can I insert the python code to trigger LED light when motion detected using RPI interface

**Comment by roberttidey** [comment]
Check out section 6.3.3 in the wiki Job Macros

motion_event.sh is called when motion detection detects a start or stop event.

The .sh file is normally a bash script but this can be changed to use python by changing the first line to #!/usr/bin/python3 . Note that this is executed by user www-data for security reasons and therefore www-data must have the appropriate permissions. For GPIO control you can adduser www-data to the gpio group. (sudo adduser www-data gpio)
