### ISSUE TITLE
Stream using VLC

### ISSUE THREAD

**Issue by ffcruz85** [silvanmelchior/RPi_Cam_Web_Interface#428]
I am trying to stream via VLC and I am getting an error when trying to stream. here are my steps:

1) In this step, I also tried to just play, getting the same error. The url works fine on the browser
![image](https://user-images.githubusercontent.com/2352828/40387937-5871404c-5dcb-11e8-828f-0bd9bd9d086e.png)
2)
![image](https://user-images.githubusercontent.com/2352828/40387950-61b0d118-5dcb-11e8-97b2-8d36b0584d58.png)
3)
![image](https://user-images.githubusercontent.com/2352828/40387962-6c571398-5dcb-11e8-8912-226c50be3847.png)
4)Tried without transcoding:
![image](https://user-images.githubusercontent.com/2352828/40387977-8113879e-5dcb-11e8-9bc2-5a62c9b67fdb.png)
5)
![image](https://user-images.githubusercontent.com/2352828/40388012-95514ebc-5dcb-11e8-97d8-964508f15834.png)
6) and with transcoding
![image](https://user-images.githubusercontent.com/2352828/40388078-be4f7e42-5dcb-11e8-839f-551a357e02ac.png)
![image](https://user-images.githubusercontent.com/2352828/40388217-1ce918b4-5dcc-11e8-8c22-134afdc9a2aa.png)

7) and just getting this error, nothing further in the log
![image](https://user-images.githubusercontent.com/2352828/40388146-ee390cd6-5dcb-11e8-80d1-e177325b52c5.png)

**Comment by roberttidey** [comment]
I use Play not Stream and it works fine on a remote Windows PC. 

I also tried stream, display locally, no transcoding and that seemed OK as well

I think your problem is you only have 1 / after http: there should be 2 as in http://10.

I have not tried running VLC on Raspberry.

**Comment by ffcruz85** [comment]
duh, sorry about that - missing the simple stuff.
So I tried that, but the image is static for some reason. it opens the stream, but it is just a static image

**Comment by ffcruz85** [comment]
got it working -  I think it might have been just a connectivity issue. Thanks again!
