### ISSUE TITLE
Multiple Vulnerabilities

### ISSUE THREAD

**Issue by reigningshells** [silvanmelchior/RPi_Cam_Web_Interface#439]
I don't want to post too much publicly, as I know a number of people who use this interface and some who have it forward facing.  There are two critical vulnerabilities I'd like to disclose.  Please reach out on Twitter @reigningshells or via email, RPi_Cam_Bugs [at] reigningshells.com.

**Comment by roberttidey** [comment]
Thanks. I have received the further details on this now.

I was planning to do some other minor updates this week(2018-08-17) so will see if I can incorporate these suggestions.

**Comment by roberttidey** [comment]
Latest version has some changes around these vulnerabilities

**Comment by reigningshells** [comment]
I sent a follow up email, just one more slight fix is necessary

**Comment by roberttidey** [comment]
I have added some extra checks which should avoid that.

I also discovered I broke some buttons when I removed the convert command dialog box so I fixed that.

**Comment by reigningshells** [comment]
Sorry, had some time to dig in and kind of flooded your inbox this evening, but I think a few more calls to checkMediaPath will solve all the issues reported tonight.

**Comment by roberttidey** [comment]
Thanks for the extra info on this. I have added the calls in to latest version.

**Comment by roberttidey** [comment]
6.4.29 has the exists call in the check function

**Comment by reigningshells** [comment]
Looks good, thanks for all your hard work!
