### ISSUE TITLE
Download Videos and Images feature request

### ISSUE THREAD

**Issue by GaryLittlemore** [silvanmelchior/RPi_Cam_Web_Interface#444]
I use the PurgeSpace_ModeEx with Min Space % set at 15%, I’d like to be able to select certain files within ‘Download Vidros and Images’ with a ‘keep’ feature so that as files are getting deleted as more files are added it doesn’t delete the files I’ve selected to be kept.

**Comment by roberttidey** [comment]
Interesting idea. I'll look into it.

It may be possible to do this by having a keep button which sets the files to read only.

**Comment by roberttidey** [comment]
Selected files can now be locked or unlocked. Locked files are read only and can't be deleted or purged. Locked files do not have the little delete icon on their thumbnail.

**Comment by GaryLittlemore** [comment]
Thanks Robert
