### ISSUE TITLE
Installation destroys root access

### ISSUE THREAD

**Issue by CoderFX** [silvanmelchior/RPi_Cam_Web_Interface#452]
Set installation folder to /home/pi/birdfeeder - installation did chown and chmod on /
Now I get:
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

**Comment by Pinsonja** [comment]
I'm having the same issue. Was yours resolved?

**Comment by roberttidey** [comment]
The install folder set during the install is intended to be a subfolder under the browser root (/var/www).

E.g setting subfolder blank means it gets installed in /var/www, or setting it to birdfeeder means it gets installed in /var/www/birdfeeder.

Trying to use a full path name as the subfolder is not a good idea.
