### ISSUE TITLE
How to get camera state?

### ISSUE THREAD

**Issue by andreluisos** [silvanmelchior/RPi_Cam_Web_Interface#461]
How could I get camera state (if recording or stopped) through CLI?

**Comment by roberttidey** [comment]
The state of the camera is maintained in the file status_mjpeg.txt. This is maintained in /dev/shm/mjpeg/status_mjpeg.txt but is linked to in the web installation folder (e.g. /var/www/html)

The web client gets this every few seconds to maintain the web status. 

You can either read it yourself or fetch it via the web interface.

**Comment by andreluisos** [comment]
Thank you!
