### ISSUE TITLE
Latest Update produces error message from schedule.php

### ISSUE THREAD

**Issue by Pi-DD** [silvanmelchior/RPi_Cam_Web_Interface#464]
Just ran the update.sh script. It found updates were needed, but restart then produced this message......

pi@DDhomepi2:~/RPi_Cam_Web_Interface $ PHP Notice:  Undefined variable: cmds in /var/www/html/schedule.php on line 469
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/schedule.php on line 469

**Comment by Pi-DD** [comment]
Thanks for the swift reaction.

As you will see from the attached screen capture Max_Capture is not set and Motion_Stop is set for certain periods on certain days. Hope that helps. 
![06a25ee3-d935-448d-bc21-570e89a0ee13](https://user-images.githubusercontent.com/38586714/50564079-1ab6a900-0d1a-11e9-80bf-02f7d2874c37.png)

**Comment by roberttidey** [comment]
I think the selective commands by days may have been part of this. The latest version should be resilient against this.

**Comment by roberttidey** [comment]
There was a typo in the first corrected version. Should be OK now.

**Comment by Pi-DD** [comment]
😁😉 I did notice a different message from PHP! Thanks for swift update.
