### ISSUE TITLE
Motion Settings: Defaults appear swapped

### ISSUE THREAD

**Issue by hazardlabs** [silvanmelchior/RPi_Cam_Web_Interface#470]
Looking at the Motion Settings tab on the main page, it appears the values for noise level and Threashold are in the wrong places. Please see the attached image

![motion_swapped_values](https://user-images.githubusercontent.com/10254256/51389284-b9694500-1b23-11e9-8ba3-2f0e2de6562c.png)

Unless the title descriptions next to them are wrong?

**Comment by roberttidey** [comment]
The parameters are the right way round but the commented range for Noise level is incorrect. 0-255 refers to a simple algorithm. Noise values above 1000 switch to a newer (better) algorithm. See in wiki under internal motion detection for a more detailed explanation.

I have amended the comment to help avoid confusion.

**Comment by hazardlabs** [comment]
Perfect, Thanks. Closing Issue
