### ISSUE TITLE
sorting issue on "download videos and images" page

### ISSUE THREAD

**Issue by wingers999** [silvanmelchior/RPi_Cam_Web_Interface#472]
Hi

Seem to only recently have issue with how items sorted on the download page - it used to be in date/time order, but now it seems completely muddled, despite sort ascending being selected

Screenshot shows what I mean better than I can explain via writing

![pi](https://user-images.githubusercontent.com/10872799/51439429-ea778000-1cb1-11e9-9c82-581cb679b9b3.png)

**Comment by roberttidey** [comment]
Your screenshot has 1 image plus 3 time lapse sets plus a bunch of videos. The page orders things as sorted images, followed by sorted time lapse, followed by sorted videos.

This has not changed. Note you can use the types filter to just show videos.

**Comment by wingers999** [comment]
Thanks Robert - never noticed it did that before!
