### ISSUE TITLE
'&' characters in UI input entries are not handled correctly

### ISSUE THREAD

**Issue by ras07** [silvanmelchior/RPi_Cam_Web_Interface#479]
Edits to either the macro filenames or the check boxes don't persist after hitting the 'OK' button. When I refresh the screen, these settings (usually) revert to their previous values. Also, the uconfig file is (usually) left unchanged.

Occasionally, it saves garbage to uconfig (for example, end_vid ▒vԅ▒v▒[▒~▒[▒~). I haven't been able to identify a repeatable set of actions that results in garbage vs. no change at all.

Manual edits to uconfig are reflected in the UI, however.

**Comment by roberttidey** [comment]
I can't reproduce that at the moment; it is working fine for me and uconfig looks ok. E.g if I change motion_event to motion_event1.sh then it appears in uconfig as 
motion_event motion_event1.sh

Which version are you running?

FIrst check the log in scheduler, you should see something like

Change: motion_event = motion_event1.sh

Next turn on developer tools in browser when you make a change then you should see a request like
cmd_pipe.php?cmd=um%208%20motion_event1.sh
where the %20 are space characters.

**Comment by ras07** [comment]
This seems really hit or miss. I just changed motion_event to motion_event1.sh and it worked. Then I tried to change end_vid to &end_vid.sh, and it instead changed it to motion_event1.sh. The request url was:
http://<myIP>/cmd_pipe.php?cmd=um%205%20&end_vid1.sh
But the log says:
`{2019/02/08 12:30:51} Change: end_vid = motion_event1.sh`
And uconfig says:
`end_vid motion_event1.sh`
Could it be related to adding the ampersand? That seems to be a common factor.
I'm running 6.4.44, and I have **enforce_lf 1** enabled, if that matters. I will continue to test.

**Comment by ras07** [comment]
Further update: it appears that the '&' symbol breaks any setting, not just the macro file names. For instance, if you set the Annotation text to have an ampersand in the middle of the string, it truncates the annotation at the ampersand (so 'MyAnnot&tion' becomes 'MyAnnot'). If the ampersand is the first character, it ends up being blank.

the URL reflects this, btw; in the above example it reads **cmd_pipe.php?cmd=an%20MyAnnot&tion**. Presumably it should translate the '&' into &amp; .

I'm going to edit the issue title appropriately.

**Comment by roberttidey** [comment]
Yes. That does seem to be a problem. & is a special character in url's. I am checking into it further

**Comment by roberttidey** [comment]
Latest version encodes the & character to prevent it being a problem.

I am checking if other characters might be problematic.

Thanks for reporting this and investigating the cause.

**Comment by roberttidey** [comment]
I think there are other problem characters like #. Will update further.

**Comment by roberttidey** [comment]
Latest now handles # and & which are the only problems discovered so far.

**Comment by ras07** [comment]
Works great - Thanks! Closing.

**Comment by ras07** [comment]
I'd like to be able to redirect the output (stdout and stderr) of macro scripts to aid in debugging. I tried setting start_vid in the UI to 
`&start_vid.sh > /var/www/macros/start_vid.out 2>&1`
but this ends up with a uconfig entry of
`start_vid &start_vid>`

It looks like two things go wrong here: First, when looking at the URL in my browser's debugging tools, it doesn't appear that it properly encodes the second '&' symbol. Second, spaces don't seem to get handled right (So even just adding a parameter to the macro ends up munging the macro name.)

When I manually edit the uconfig file to 
`start_vid &start_vid.sh > /var/www/macros/start_vid.out 2>&1`
it does indeed appear to redirect the output as desired (although I haven't tested this extensively).

**Comment by roberttidey** [comment]
I have changed it to handle multiple & or # characters.

Space characters in those commands are different. I'll look further into that but it wasn't really intended to put command lines in there. You could use 1 batch file to call another with the extra debug parameters.

**Comment by ras07** [comment]
I understand (FWIW, though, it does seem to work (with the spaces) when I manually edit the uconfig file)

**Comment by ras07** [comment]
(Also: the plus character '+' doesn't seem to work either)

**Comment by roberttidey** [comment]
+ characters are normally treated as spaces in urls. I have escaped that as well.

The problem with space characters is that is used as the field separator between parameters in the pipe commands. This only caused a problem with the um command used to define macros.

Latest version handles + and allows spaces in macro definitions

**Comment by ras07** [comment]
Thank you!
