### ISSUE TITLE
Forgot to turn on jpglink during setup

### ISSUE THREAD

**Issue by TheVillageGuy** [silvanmelchior/RPi_Cam_Web_Interface#504]
Is there a way to turn it on by hand?

Running 6.5.1

Thanks!

Village

**Comment by roberttidey** [comment]
The following assumes install into html subfolder, adjust paths if necessary

Make sure there is no cam.jpg in the www install folder (e.g. /var/www/html/cam.jpg) Delete it if necessary (sudo rm /var/www/html/cam.jpg)

Then run 

sudo ln -sf /dev/shm/mjpeg/cam.jpg /var/www/html/cam.jpg

now make sure everything is owned by www-data

sudo chown www-data:www-data /var/www/html

**Comment by TheVillageGuy** [comment]
That did it thanks
