### ISSUE TITLE
Not asking for Username & Password

### ISSUE THREAD

**Issue by eldad-a** [silvanmelchior/RPi_Cam_Web_Interface#509]
First, I would like to thank the contributors for this helpful interface!

This issue may be related to: #309

**Issue**
When connecting to RPi_Cam_Web_Interface, no user and password were requested.
The matter seems to be related to choosing a web port different from the default 80.
This was done using the installer interface.

**Solution**
Modify the configuration file, found at `/etc/apache2/sites-available/raspicam.conf`
replacing `80` in `<VirtualHost *:80>` for the desired port.

Reboot --> User and Password are now requested for login.

**Question**
Should this be the solution?
Can this modification be added to the installation pipeline?

**Details**

1. Fresh install of Rasbian, [noobs](https://www.raspberrypi.org/downloads/noobs/) 3.2.0, dated 2019-07-10.

2. `sudo apt install  vim-gtk3 byobu htop` followed by `update-alternatives --set editor /usr/bin/vim.tiny`

3. Setup a new admin and remove the ‘pi’ user

4. Using `raspi-config` made the machine headless (activating SSH and deactivating auto-gui desktop).

5. [Passwordless SSH access](https://www.raspberrypi.org/documentation/remote-access/ssh/passwordless.md)

6. [Adding the network details to the Raspberry Pi](https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md)

7. Install RPi_Cam_Web_Interface following [RPi-Cam-Web-Interface#Basic_Installation](https://elinux.org/RPi-Cam-Web-Interface#Basic_Installation). Using `install.sh` chose the defaults other than the web port, user and password.

8. Only after modifying `/etc/apache2/sites-available/raspicam.conf`, replacing the `80` in `<VirtualHost *:80>`, and a reboot, did the server start requesting user and password.

**Comment by roberttidey** [comment]
There was a line in the install.sh that does try to set up the Virtual Host port number to that specified.

Unlike the other lines doing similar things this didn't run under sudo. I am not sure if that was the reason but I changed it anyway in the latest version.

If that doesn't fix it I'll have to dig deeper.

**Comment by roberttidey** [comment]
Hmm. I just did a test by pulling latest git and set to port 90. The /etc/apache2/sites-available/raspicam.conf showed the port had been set to 90 as expected.

Can you try running the following command from your home directory?

`sudo awk '/<VirtualHost \*:/{c+=1}{if(c==1){sub("<VirtualHost \*:.*","<VirtualHost *:'90'>",$0)};print}' RPi_Cam_Web_Interface/etc/apache2/sites-available/raspicam.conf.1 > tmpfile`

This is similar to the command used in the install.sh but just produces a tmpfile in the home directory. This should be the raspicam.conf file but with port changed to 90

**Comment by eldad-a** [comment]
If I understand correctly the desired outcome, it currently does not work. 
Sorry I am not familiar with `awk`... it makes it more difficult to help in the debugging process.

Here's what I find running the command (with the exception that I dropped the `sudo`):

Output:
> awk: cmd. line:1: warning: escape sequence \`\*' treated as plain `*'

and the files are attached

[raspicam_conf_port_debugging.zip](https://github.com/silvanmelchior/RPi_Cam_Web_Interface/files/3557536/raspicam_conf_port_debugging.zip)

**Comment by roberttidey** [comment]
That is strange. I just took the raspicam.conf.1 file you sent and placed it in my home directory.

I then ran 

`sudo awk '/<VirtualHost \*:/{c+=1}{if(c==1){sub("<VirtualHost \*:.*","<VirtualHost *:'90'>",$0)};print}' raspicam.conf.1 > tmpfile`

which runs same command but assuming the raspicam.conf.1 is in the home directory and my tmpfile then had the 80 changed to 90.

Can you repeat ( and use sudo)? If it fails can you screen shot the command window showing the command and the error?

**Comment by eldad-a** [comment]
Thanks for your help!

The port number in the tmpfile was not modified (despite using `sudo`).
Please see the attached files.

![Screenshot from 2019-08-30 11-29-26_](https://user-images.githubusercontent.com/3859135/64044076-d71b7580-cb1a-11e9-9a0e-4e63c033d1a0.png)
[raspicam_conf_port_debugging_20190830.zip](https://github.com/silvanmelchior/RPi_Cam_Web_Interface/files/3561124/raspicam_conf_port_debugging_20190830.zip)


Additionally:

```BASH
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```
```BASH
$ awk -V
GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.1.2)
Copyright (C) 1989, 1991-2018 Free Software Foundation.
...
```

**Comment by roberttidey** [comment]
As your use of sudo is prompting for a password then you must have some special set up as normally the user pi has sudo privileges and does not do this.

Has this user got bash as its default shell? That might have something to do with it.

I think the error you see is being triggered by a different handling of the command such that it is being scanned twice. This means on the first pass the second escaped char \* is being converted to * on the first scan and then when it is executed for real then the * is not escaped.

To prove this try adding an extra slash just for the second instance (the one inside the quotes) e.g.
` sudo awk '/<VirtualHost \*:/{c+=1}{if(c==1){sub("<VirtualHost \\*:.*","<VirtualHost *:'90'>",$0)};print}' raspicam.conf.1 > tmpfile
`

If that works then I will have to check that is OK for standard set ups and there may be other instances of the same thing elsewhere in the install.sh file.

**Comment by eldad-a** [comment]
> As your use of sudo is prompting for a password then you must have some special set up as normally the user pi has sudo privileges and does not do this.

I have removed the `pi` user from the system. 
A new user was created based on the following  [link](https://www.raspberrypi.org/documentation/linux/usage/users.md):
1. `sudo adduser <username>` , and
2.  `sudo visudo` followed by  adding a new line: `<username>  ALL=(ALL:ALL) ALL`

> Has this user got bash as its default shell? 

Yes:
```BASH
$ env |grep -i shell
SHELL=/bin/bash
```
>That might have something to do with it.
> 
> I think the error you see is being triggered by a different handling of the command such that it is being scanned twice. This means on the first pass the second escaped char * is being converted to * on the first scan and then when it is executed for real then the * is not escaped.
> 
> To prove this try adding an extra slash just for the second instance (the one inside the quotes) e.g.
> `sudo awk '/<VirtualHost \*:/{c+=1}{if(c==1){sub("<VirtualHost \\*:.*","<VirtualHost *:'90'>",$0)};print}' raspicam.conf.1 > tmpfile`
> 
This one works !
`tmpfile` now reads:
` <VirtualHost *:90>`
for its first line.

> If that works then I will have to check that is OK for standard set ups and there may be other instances of the same thing elsewhere in the install.sh file.

Just for completeness, I ran `sudo -i` to switch to `root` with its own setup.
The original command (from the previous posts, without the extra slash), behaved like it did before, that is, does not modify the port number and leaves it as `80`.

**Comment by roberttidey** [comment]
I am not sure why your system behaves differently but I have changed install.sh (and remove.sh) so it should work either way.

**Comment by eldad-a** [comment]
Many thanks for all your help!
**Solved** :-)

`git pull` --> now @ commit `cd1ed78`:

raspicam.conf now shows the desired port number  when running install.sh with a modified web port. 

Seems good to close this issue.

**Comment by thc2018** [comment]
Sorry, I have this issue. I can give url to everyone, and he/she will be able to see cameras and obtain a full rights

**Comment by roberttidey** [comment]
I am not quite sure what you are asking.

Have you set up username and password when installing the software? You can run the installer again if necessary to add this.

I recommend using Apache if wanting to use security.

With basic set up then all users who enter the user / password can then fully access the camera. It is then possible to set it up so that different users have different access ranging from just preview up to full control. Check wiki out to get started on that
