### ISSUE TITLE
6.6.3 fails to run due to missing element

### ISSUE THREAD

**Issue by Pi-DD** [silvanmelchior/RPi_Cam_Web_Interface#515]
Upgraded to 6.6.3 and got this message....

`raspimjpeg: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by raspimjpeg)`

**Comment by roberttidey** [comment]
You may get this if you are on Stretch OS and didn't change php version to 7.1.

Set up defaults are for Buster and php 7.3

**Comment by Pi-DD** [comment]
Thanks, I’m attempting a direct Buster update - bold! (because I don’t have the ready means of starting from a new SD at this remote location)
I’ll update news when done!

**Comment by Pi-DD** [comment]
Now updated to Buster and 6.6.4. 

Runs, but video not boxed, see

https://github.com/silvanmelchior/RPi_Cam_Web_Interface/issues/516
