### ISSUE TITLE
Full Screen mode shows webpage background

### ISSUE THREAD

**Issue by jarrah31** [silvanmelchior/RPi_Cam_Web_Interface#539]
Hi Robert,

If I manually trigger full screen by clicking the live video image, the web page background either side of the video is plain white.

However, if I use the `fullscreen true` setting in /etc/raspimjpeg and reload the page, I can see the horizontal menu bars and black title bar in the background.
e.g.
<img width="524" alt="image" src="https://user-images.githubusercontent.com/3072303/73126247-32597300-3fa8-11ea-8fee-93164195aced.png">

Do you know if it's possible to fix this by any chance please?

I'm triggering a video feed of my front door camera on a tablet by the door when motion is detected, and it would just look neater if the background was plain. :) 

TIA

**Comment by roberttidey** [comment]
Yes. The fullscreen config does not do the same thing as the client click. This is because the config controls what the webserver delivers and the client click does some actions via javascript in the client itself.

I will have a look to see if the server side can be made similar.

**Comment by roberttidey** [comment]
I forgot there was a change put in some time ago that allows the start up to be varied according to the url used.

If you use raspiIp/index.php#full then it will start up in full screen mode just like if you clicked at the client.

**Comment by jarrah31** [comment]
Works a treat, thank you very much!
