### ISSUE TITLE
How to get the HD mjpeg stream for OpenCV?

### ISSUE THREAD

**Issue by xubury** [silvanmelchior/RPi_Cam_Web_Interface#554]
I tried and used `http://myipaddress/html/cam_pic_new.php`, but it return a low-res image feed. The page setting is 1080p though. How do I get that 1080p stream properly?

**Comment by roberttidey** [comment]
The stream is controlled by the preview parameters. The preview width controls the resolution. Height is set automatically by the aspect ratio of the video parameters. Default width is 500 but you can set that higher e.g. 1080 to get a higher resolution stream. This will increase the required network bandwidth to support the stream.

**Comment by xubury** [comment]
@roberttidey yes, thanks for the tip! Now I can get HD stream. Great project!
