### ISSUE TITLE
Setting $rpicamdir to a non empty value breakes calling the scheduler from rc.local

### ISSUE THREAD

**Issue by rebos** [silvanmelchior/RPi_Cam_Web_Interface#59]
Hi,

changing $rpicamdir in the installer script to a non empty value results in a broken call for the scheduler in rc.local. Setting it to "rpicam", for example, produces the following line due to the modification with sed:  

    sleep 4;su www/rpicam-data -c 'php /var/www/schedule.php > /dev/null &'

A potential fix could be changing the sed expression in line 132 in the following way:

    sed -e "s/\/var\/www/\/var\/www\/$rpicamdir/" etc/rc_local_run/rc.local.1 > etc/rc_local_run/rc.local

This would produce the following line concerning the scheduler call:

    sleep 4;su www-data -c 'php /var/www/rpicam/schedule.php > /dev/null &'

Greetings,
rebos

**Comment by roberttidey** [comment]
Thanks for that. Merged into repo.
