### ISSUE TITLE
Remove.sh

### ISSUE THREAD

**Issue by XVD-XVD** [silvanmelchior/RPi_Cam_Web_Interface#596]
remove.sh: 101: remove.sh: Syntax error: "(" unexpected (expecting ";;")

**Comment by sbkomurcu** [comment]
Which command did you use to execute the script?

**Comment by XVD-XVD** [comment]
Sudo ./remove.sh

**Comment by sbkomurcu** [comment]
However not being sure, last time I had similar issue and I overcome by using either `sudo sh remove.sh` or `./remove.sh`. You can also try uninstalling by using `RPi_Cam_Web_Interface_Installer.sh`.

**Comment by XVD-XVD** [comment]
I solved it by removing the folder and the apache2 folder and then its fixed,but i wanted to allert you with the problem.
