### ISSUE TITLE
does RPCWI have a network port signature?

### ISSUE THREAD

**Issue by BETLOG** [silvanmelchior/RPi_Cam_Web_Interface#603]
Does RPCWI have some kind of unique response to queries that I could use to determine which LAN machines actually have it installed and running on them?
Ideally I'd like to be able to spend no more than 1 second querying each machine with something like nc, and conclusively determine if RPCWI is operational on them or not.

**Comment by roberttidey** [comment]
If you use nc to the port that the web server is supposed to be running on to determine that port is open then doing a wget from ip/html/status_mjpeg.txt would return a single word with the current status which could be
"Error"
"halted"
"image"
"tl_video"
"video"
"tl_md_video"
"timelapse"
"ready"
"tl_md_ready"
"md_ready"

If the web server is running but no RPCWI installed then you would get file not found error.
