### ISSUE TITLE
Support for split screen

### ISSUE THREAD

**Issue by MohammedRehabS** [silvanmelchior/RPi_Cam_Web_Interface#620]
We need a split screen kind of video feed of the same camera on the webpage, how is it possible to do that?

**Comment by roberttidey** [comment]
You will have to provide some more detail on what you are trying to achieve. Split screen is too ambiguous.

**Comment by MohammedRehabS** [comment]
We need something which could give a VR like view . So we need two streams of the same camera side by side. Something like a split screen mode.

**Comment by roberttidey** [comment]
If you want two stream windows showing identical content side by side then you should be able to achieve that by editing the index.php page and creating a second preview window (see around line 299 img mjpeg_dest). This would need a separate id. Then in the javascript script.js then the updatePreview function would need editing to also update this second img object.

**Comment by MohammedRehabS** [comment]
Worked out perfectly , thank you very much. 

Can you please tell us how can we achieve multiuser login as well.

**Comment by roberttidey** [comment]
In the wiki see section 4.11 and 4.15

**Comment by MohammedRehabS** [comment]
Thank you very much
