### ISSUE TITLE
Problem with Filter dropdown on preview.php page

### ISSUE THREAD

**Issue by wn-dev** [silvanmelchior/RPi_Cam_Web_Interface#624]
The Filter dropdown on the preview.php page doesn't allow selecting files that are between 144 and 192 hours old.  There's an option for "120-144 hours old" and an option for "192+ hours old", but nothing in-between.  See the red-circled section in the below screenshot.  Maybe the option for "192+ hours old" can be changed to "144+ hours old" to fix this problem?

![image](https://user-images.githubusercontent.com/76469916/123224276-89f25b80-d486-11eb-800a-cf062057be17.png)

**Comment by roberttidey** [comment]
Thanks for pointing this out. This list labels are calculated on the fly and there was a coding error for the last entry. It was actually 144+ despite its label.

Corrected in latest version

**Comment by wn-dev** [comment]
@roberttidey Thanks for fixing the label problem.  Using the latest code, selecting the "144+ hours old" filter results in files aged 168+ hours being shown in the results.  Files aged 144 to 168 hours are missing in the results, which suggests that the filtering logic for this case is off by 24 hours.

**Comment by roberttidey** [comment]
OK. Checking into that further.

**Comment by roberttidey** [comment]
I think latest version now corrects this.

**Comment by wn-dev** [comment]
Yes, the latest version fixes the problem.  Thanks @roberttidey for the quick resolution.
