### ISSUE TITLE
Web interface "Forbidden" massage

### ISSUE THREAD

**Issue by markxyx** [silvanmelchior/RPi_Cam_Web_Interface#639]
I am getting this a lot on web interface. About one or twice in an hour. Rebooting will fix this and gain access again. Is there any way to prevent this?

Forbidden
You don't have permission to access this resource.

Apache/2.4.38 (Raspbian) Server at 192.168.1.20 Port 80

**Comment by roberttidey** [comment]
I don't think this is directly related to the server side; I have never had this in many years of operation on multiple cameras.

I suspect it is browser related in some way. What browser are you using?

The best way to get further information on what is going on is to turn on developers tools in the browser and you should then get detailed information on what has triggered that error.
