### ISSUE TITLE
Annotation after reboot

### ISSUE THREAD

**Issue by Fritz4all** [silvanmelchior/RPi_Cam_Web_Interface#66]
I wanted to create some time-lapse series without annotations in them so i cleared the annotation text box like shown in the picture below : 
![annotation settings](https://cloud.githubusercontent.com/assets/7778422/7720005/1c8a7162-fec8-11e4-8edf-a9ff38e4b9fb.JPG)

Everything worked like it should until a system reboot. 

When i reboot the system the annotation is back, but the annotation config field is still empty : 

![annotation settings after reboot](https://cloud.githubusercontent.com/assets/7778422/7720010/4ab7401a-fec8-11e4-8b60-55c8a97f8c68.JPG)

when i press "record image" after a reboot the annotation is embedded in the image and the thumbnail image : 

![im_0000_20150520_083225 jpg i0000 th](https://cloud.githubusercontent.com/assets/7778422/7720340/6b6db9fc-fecc-11e4-93bd-30691649bef6.jpg)

Clearing the annotation text box even when it is already empty and pressing OK removes the annotations again.

My configuration : 
```
Raspberry Pi Model B (512MB)
 - latest official Rasbian image 
 - Kernel 3.18.11+ #781
 - All other software up to date.
 - RPi Cam Control v5.1.7
The Raspberry Pi camera module 1.3
```

@silvanmelchior great project.

**Comment by bmedicke** [comment]
As a workaround you can paste a single `%` into the annotations box (or set it in uconfig).

**Comment by Fritz4all** [comment]
@bmedicke tnx, a single ```%``` works.

**Comment by roberttidey** [comment]
Thanks for posting the work-around. It looks like there is a an issue when raspimjpeg loads uconfig with totally blank fields. It is accepting the command when doing it live but the reload that occurs when it is restarted or after a bot causes the issue. I'll check into that.

**Comment by roberttidey** [comment]
Fixed in latest version
